### ISSUE TITLE
Buy now using payex button showing when plugin is not active

### ISSUE THREAD

**Issue by sjobidoo** [PayEx/PayEx.Checkout.WooCommerce#1]
The "Buy now using payex" button on product page is being shown even though the plugin is not enabled in the cart settings of WooCommerce.

Also: the text displayed on the button seems to not be translatable?

Feature suggestion:  add option to choose if we wish to display the "buy now using payex" button or not.

**Comment by olegisk** [comment]
Implemented here https://github.com/PayEx/PayEx.Checkout.WooCommerce/commit/da43cb2548d118f99ce901df7ee287cf2e1afc2c

**Comment by olegisk** [comment]
You can translate text using poeditor. Use langauges/woocommerce-payex-checkout-sv_SE.po
